### ISSUE TITLE
Incorrect instructions in README.md

### ISSUE THREAD

**Issue by bryceprutsos** [smashie420/Epic-Games-Today-Free-Day#1]
**Describe the bug**
In your README.md for Windows is says 
git clone https://github.com/smashie420/Epic-Games-Today-Free-Day
cd Epic-Games-Today-Free-Day
npm install
node index.js

the last line should say  node install.js instead of index.js 

PS you should make one for humble bundle this was by far the best project I have seen for discord and epic games

**Comment by smashhub-dev** [comment]
Updated README.md

Thank you for the issue!
